baseURL = 'https://honeynet.org/'
languageCode = 'en-us'
title = 'The Honeynet Project'

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'About Us'
  pageRef = '#'
  weight = 20
[[menu.main]]
  name = 'The Project'
  parent = 'About Us'
  pageRef = '/about'
  weight = 20
[[menu.main]]
  name = 'News'
  pageRef = '/blog'
  weight = 30
[[menu.main]]
  name = 'GSoC'
  pageRef = '/gsoc'
  weight = 40
[[menu.main]]
  parent = 'GSoC'
  name = 'GSoC 2023'
  pageRef = '/gsoc/2023'
  weight = 20
# TODO: Previous GSoC years
[[menu.main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 50
[[menu.main]]
  name = 'FAQ'
  pageRef = '/faq'
  weight = 60
[[menu.main]]
  name = 'Workshops'
  pageRef = '/workshops'
  weight = 70
[[menu.main]]
  name = 'Challenges'
  pageRef = '/challenges'
  weight = 80
