permissions:
  contents: read

on:
  push:
    branches:
      - main
      - v2
  schedule:
    - cron: '27 3,9,15,21 * * *'

jobs:
  deploy:
    uses: mhils/workflows/.github/workflows/gh-pages-hugo.yml@v2
    permissions:
      contents: read
      id-token: write
      pages: write
